name: E2E

on: [push]

env:
  CI: true
  TZ: UTC
  E2E_TEST: 1
  NODE_ENV: ci
  PGHOST: localhost
  PGUSER: postgres
  WEBSITE_URL: http://localhost:3000
  IMAGES_URL: http://localhost:3001
  API_URL: http://localhost:3060
  API_KEY: dvl-1510egmf4a23d80342403fb599qd
  CYPRESS_RECORD: false
  CYPRESS_VIDEO: false
  CYPRESS_VIDEO_UPLOAD_ON_PASSES: false
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  FRONTEND_FOLDER: /home/runner/work/opencollective-frontend/opencollective-frontend
  API_FOLDER: /home/runner/work/opencollective-frontend/opencollective-frontend/opencollective-api
  IMAGES_FOLDER: /home/runner/work/opencollective-frontend/opencollective-frontend/opencollective-images
  TERM: xterm
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  e2e:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        files: ['0*.js', '1*.js', '2*.js', '3*.js']

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      postgres:
        image: mdillon/postgis:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Update apt
        run: sudo apt-get update || exit 0

      - name: Install Cypress dependencies
        run: sudo apt-get install --no-install-recommends -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gbsn00lp fonts-arphic-gkai00mp fonts-arphic-ukai fonts-arphic-uming ttf-wqy-zenhei ttf-wqy-microhei xfonts-wqy

      - name: Install postgresql-client
        run: sudo apt-get install -y postgresql-client

      - name: Install graphicsmagick
        run: sudo apt-get install -y graphicsmagick

      # - name: Setup node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'

      # Npm cache

      - name: Restore .npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ github.sha }}
          restore-keys: |
            - ${{ runner.os }}-npm-cache-${{ github.sha }}
            - ${{ runner.os }}-npm-cache-

      # Checkouts

      - name: Checkout (frontend)
        uses: actions/checkout@v2-beta

      - name: Check matching branch (api)
        id: check-matching-branch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/git/:ref
          owner: opencollective
          repo: opencollective-api
          ref: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Checkout (api - matching branch)
        if: steps.check-matching-branch.outputs.status == 200
        uses: actions/checkout@v2-beta
        with:
          repository: opencollective/opencollective-api
          path: opencollective-api
          ref: ${{ github.ref }}

      - name: Checkout (api - master)
        if: steps.check-matching-branch.outputs.status != 200
        uses: actions/checkout@v2-beta
        with:
          repository: opencollective/opencollective-api
          path: opencollective-api

      - name: Checkout (images)
        uses: actions/checkout@v2-beta
        with:
          repository: opencollective/opencollective-images
          path: opencollective-images

      # Prepare API

      - name: Restore node_modules (api)
        uses: actions/cache@v1
        id: api-node-modules
        with:
          path: opencollective-api/node_modules
          key: ${{ runner.os }}-api-node-modules-${{ hashFiles('opencollective-api/package-lock.json') }}

      - name: Install dependencies (api)
        working-directory: opencollective-api
        if: steps.api-node-modules.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      - name: Build (api)
        working-directory: opencollective-api
        run: npm run build

      # Prepare Images

      - name: Restore node_modules (images)
        uses: actions/cache@v1
        id: images-node-modules
        with:
          path: opencollective-images/node_modules
          key: ${{ runner.os }}-images-node-modules-${{ hashFiles('opencollective-images/package-lock.json') }}

      - name: Install dependencies (images)
        working-directory: opencollective-images
        if: steps.images-node-modules.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      - name: Build (images)
        working-directory: opencollective-images
        run: npm run build

      # Prepare Frontend

      - name: Restore node_modules (frontend)
        uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (frontend)
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - name: Restore Cypress
        uses: actions/cache@v1
        id: cypress
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('node_modules/cypress/package.json') }}

      - name: Install Cypress
        if: steps.cypress.outputs.cache-hit != 'true'
        run: npx cypress install

      - name: Restore .next build (frontend)
        uses: actions/cache@v1
        id: next-build
        with:
          path: .next
          key: ${{ runner.os }}-next-build-${{ github.sha }}

      - name: Restore .next cache (frontend)
        if: steps.next-build.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-cache-${{ github.sha }}
            ${{ runner.os }}-next-cache-

      - name: Build (frontend)
        if: steps.next-build.outputs.cache-hit != 'true'
        run: npm run build

      - name: Setup DB
        run: ./scripts/setup_db.sh

      - name: Run E2E with Cypress
        run: ./scripts/run_e2e_tests.sh
        env:
          CYPRESS_TEST_FILES: ${{ matrix.files }}

      - name: Report Coverage
        run: npm run test:coverage
